<x-theme.app title="{{ $title }}" table="Y" sizeCard="11">
    <x-slot name="cardHeader"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><div><h5 class="mb-1">Setor Penjualan Ayam</h5><small class="text-muted">Jurnal masuk ke jurnal perkiraan dengan kredit akun Penjualan Ayam.</small></div><a href="{{ route('penjualan_ayam.index') }}" class="btn btn-outline-primary btn-sm"><i class="fas fa-arrow-left me-1"></i> Kembali</a></div></x-slot>
    <x-slot name="cardBody">
        <style>.ayam-setor-info{padding:15px;border:1px solid #dce4f2;border-radius:12px;background:#f7f9fd}.ayam-setor-table{overflow-x:auto;border:1px solid #dce4f2;border-radius:12px}.ayam-setor-table table{min-width:760px;margin:0}.ayam-setor-table th{padding:11px;background:#304f9e!important;color:#fff!important}.ayam-setor-table td{padding:11px;vertical-align:middle}.ayam-jurnal{padding:16px;border:1px solid #dce4f2;border-radius:12px;background:#fff}.ayam-total{color:#18366f;font-size:22px;font-weight:700}.select2-container{width:100%!important}</style>
        @if(isset($errors) && $errors->any())<div class="alert alert-danger"><strong>Data belum dapat disimpan.</strong><br>{{ $errors->first() }}</div>@endif
        @php($total = $invoice->sum(fn($row) => (float)$row->qty * (float)$row->h_satuan))
        <div class="ayam-setor-info mb-3"><strong>{{ $nota->no_nota }}</strong> · {{ tanggal($nota->tgl) }} · {{ $nota->nama_customer }}</div>
        <div class="ayam-setor-table mb-3"><table class="table table-hover"><thead><tr><th>Nota</th><th>Customer</th><th class="text-end">Qty</th><th class="text-end">Harga satuan</th><th class="text-end">Total</th></tr></thead><tbody>@foreach($invoice as $item)<tr><td>{{ $item->no_nota }}</td><td>{{ $item->nama_customer }}</td><td class="text-end">{{ number_format($item->qty,0,',','.') }} ekor</td><td class="text-end">Rp {{ number_format($item->h_satuan,0,',','.') }}</td><td class="text-end fw-bold">Rp {{ number_format($item->qty*$item->h_satuan,0,',','.') }}</td></tr>@endforeach</tbody></table></div>
        <form action="{{ route('penjualan_ayam.save_cek') }}" method="POST">@csrf<input type="hidden" name="urutan" value="{{ $nota->urutan }}">
            <div class="ayam-jurnal row g-3 align-items-end"><div class="col-md-7"><label class="form-label fw-bold">Akun pembayaran (Debit)</label><select name="id_akun_pembayaran" class="form-select select2" required><option value="">Pilih kas, bank, atau piutang</option>@foreach($akun as $a)<option value="{{ $a->id_akun_perkiraan }}" @selected(old('id_akun_pembayaran')==$a->id_akun_perkiraan)>{{ $a->kode_perkiraan }} - {{ $a->nama }}</option>@endforeach</select><small class="text-muted">Jika belum dibayar, pilih akun Piutang.</small></div><div class="col-md-5 text-md-end"><small class="text-muted d-block">Kredit: Penjualan Ayam</small><span class="ayam-total">Rp {{ number_format($total,0,',','.') }}</span></div>
                <div class="col-12"><div class="alert alert-light border mb-0"><div class="d-flex justify-content-between"><span>Debit — akun pembayaran</span><strong>Rp {{ number_format($total,0,',','.') }}</strong></div><div class="d-flex justify-content-between mt-2"><span>Kredit — Penjualan Ayam</span><strong>Rp {{ number_format($total,0,',','.') }}</strong></div></div></div>
                <div class="col-12 text-end"><button class="btn btn-primary px-4" onclick="return confirm('Simpan penjualan ayam ini ke jurnal perkiraan?')"><i class="fas fa-save me-1"></i> Simpan ke Jurnal Perkiraan</button></div>
            </div>
        </form>
    </x-slot>
    @section('scripts')<script>$(function(){ $('.select2').select2({width:'100%'}); });</script>@endsection
</x-theme.app>
