<x-theme.app title="{{ $title }}" table="Y" sizeCard="12" cont="container-fluid">
    <x-slot name="cardHeader">
        <div class="d-flex justify-content-between align-items-center flex-wrap gap-2">
            <div><h5 class="mb-0">CV AGRI LARAS</h5><small>{{ $title }}</small></div>
            <a href="{{ route('laporan') }}" class="btn btn-light btn-sm"><i class="fas fa-arrow-left me-1"></i> Daftar Laporan</a>
        </div>
    </x-slot>
    <x-slot name="cardBody">
        <style>
            .cash-filter{padding:16px;border:1px solid #dce4f2;border-radius:12px;background:#f7f9fd}.cash-table-wrap{height:calc(100vh - 355px);min-height:420px;overflow:auto;border:1px solid #dce4f2;border-radius:12px}.cash-table{min-width:1250px}.cash-table thead th{position:sticky;top:0;z-index:4;background:#435ebe;color:#fff;white-space:nowrap}.cash-table tbody td{vertical-align:middle}.cash-table tbody td:first-child,.cash-table thead th:first-child{position:sticky;left:0;z-index:3;background:#fff}.cash-table thead th:first-child{background:#435ebe;z-index:5}.cash-table .section-row td{background:#eef2f7;font-weight:700}.cash-table .total-row td{border-top:2px solid #52606d;font-weight:700}.cash-table .amount{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.cash-table .amount a{color:#3457b2;text-decoration:none;border-bottom:1px dotted #3457b2}.cash-table .amount a:hover{color:#18366f;border-bottom-style:solid}.cash-kpi{height:100%;padding:15px 18px;border:1px solid #e2e8f3;border-radius:12px;background:#fff;box-shadow:0 4px 14px rgba(40,65,120,.06)}.cash-kpi small{display:block;color:#7583a0;font-size:11px;text-transform:uppercase;letter-spacing:.5px}.cash-kpi strong{display:block;margin-top:4px;color:#18366f;font-size:20px}.cash-kpi.net strong{color:#16834b}@media(max-width:575px){.cash-table-wrap{height:calc(100vh - 430px);min-height:360px}.cash-filter .btn{width:100%}}
        </style>
        @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="get" class="cash-filter mb-3">
            <div class="row g-2 align-items-end">
                <div class="col-lg-4"><label class="form-label fw-semibold">Akun kas / bank (bisa pilih beberapa)</label><select name="akun[]" class="form-select select2" multiple data-placeholder="Pilih akun kas/bank">@foreach($cashAccounts as $account)<option value="{{ $account->id_akun_perkiraan }}" @selected($selectedAccounts->contains('id_akun_perkiraan',$account->id_akun_perkiraan))>{{ $account->kode_perkiraan }} - {{ $account->nama }}</option>@endforeach</select></div>
                <div class="col-sm-2"><label class="form-label fw-semibold">Dari bulan</label><select name="bulan_dari" class="form-select">@foreach($months as $number=>$name)<option value="{{ $number }}" @selected($start->month===$number)>{{ $name }}</option>@endforeach</select></div>
                <div class="col-sm-2"><label class="form-label fw-semibold">Tahun</label><select name="tahun_dari" class="form-select">@foreach($years as $year)<option value="{{ $year }}" @selected($start->year===$year)>{{ $year }}</option>@endforeach</select></div>
                <div class="col-sm-2"><label class="form-label fw-semibold">Sampai bulan</label><select name="bulan_sampai" class="form-select">@foreach($months as $number=>$name)<option value="{{ $number }}" @selected($end->month===$number)>{{ $name }}</option>@endforeach</select></div>
                <div class="col-sm-2"><label class="form-label fw-semibold">Tahun</label><select name="tahun_sampai" class="form-select">@foreach($years as $year)<option value="{{ $year }}" @selected($end->year===$year)>{{ $year }}</option>@endforeach</select></div>
                <div class="col-12 d-flex justify-content-end"><button class="btn btn-primary"><i class="fas fa-filter me-1"></i> Tampilkan Laporan</button></div>
            </div>
        </form>
        @if($result)
            @php $fmt=fn($value)=>'Rp '.number_format((float)$value,0,',','.'); $periods=$result['periods']; $akunKasDetail=$selectedAccounts->pluck('id_akun_perkiraan')->all(); @endphp
            <div class="mb-3"><h5 class="mb-1">Laporan Arus Kas</h5><div class="text-muted">{{ $selectedAccounts->map(fn($a)=>$a->kode_perkiraan.' - '.$a->nama)->implode(' | ') }} · {{ $start->translatedFormat('d F Y') }} s/d {{ $end->translatedFormat('d F Y') }}</div></div>
            <div class="row g-3 mb-4"><div class="col-md-3"><div class="cash-kpi"><small>Saldo awal</small><strong>{{ $fmt($result['openingBalance']) }}</strong></div></div><div class="col-md-3"><div class="cash-kpi"><small>Total arus masuk</small><strong>{{ $fmt($result['totalIncoming']) }}</strong></div></div><div class="col-md-3"><div class="cash-kpi"><small>Total arus keluar</small><strong>{{ $fmt($result['totalOutgoing']) }}</strong></div></div><div class="col-md-3"><div class="cash-kpi net"><small>Saldo akhir</small><strong>{{ $fmt($result['closingBalance']) }}</strong></div></div></div>
            <div class="d-flex justify-content-between align-items-end mb-2"><div><label class="form-label mb-1">Cari akun lawan</label><div class="input-group"><span class="input-group-text"><i class="fas fa-search"></i></span><input id="cariArusKas" type="search" class="form-control" placeholder="Ketik kode atau nama akun..."></div></div><small id="hasilArusKas" class="text-muted"></small></div>
            <div class="cash-table-wrap"><table class="table table-sm cash-table align-middle mb-0"><thead><tr><th style="min-width:310px">Akun Lawan</th>@foreach($periods as $period)<th class="amount" style="min-width:145px">{{ $months[$period->month] }} {{ $period->year }}</th>@endforeach<th class="amount" style="min-width:155px">Total</th></tr></thead><tbody>
                <tr class="section-row"><td colspan="{{ $periods->count()+2 }}">ARUS KAS MASUK</td></tr>
                @foreach($result['incomingRows'] as $row)<tr class="cash-account-row" data-search="{{ strtolower($row['kode'].' '.$row['nama']) }}"><td><strong>{{ $row['nama'] }}</strong><small class="d-block text-muted">{{ $row['kode'] }}</small></td>@foreach($periods as $period)@php $amount=$row['values'][$period->format('Y-m')] ?? 0; $detailParams=['akun_kas'=>$selectedAccount->id_akun_perkiraan,'akun_lawan'=>$row['id'],'kategori'=>$row['kategori_utang'] ?? '','nilai'=>$amount,'tanggal_awal'=>$period->copy()->startOfMonth()->toDateString(),'tanggal_akhir'=>$period->copy()->endOfMonth()->toDateString()]; @endphp<td class="amount">@if($row['id'])<a href="{{ route('jurnal-perkiraan.arus-kas-detail',$detailParams) }}" title="Lihat transaksi arus kas">{{ $fmt($amount) }}</a>@else{{ $fmt($amount) }}@endif</td>@endforeach@php $detailParams=['akun_kas'=>$selectedAccount->id_akun_perkiraan,'akun_lawan'=>$row['id'],'kategori'=>$row['kategori_utang'] ?? '','nilai'=>$row['total'],'tanggal_awal'=>$start->toDateString(),'tanggal_akhir'=>$end->toDateString()]; @endphp<td class="amount fw-bold">@if($row['id'])<a href="{{ route('jurnal-perkiraan.arus-kas-detail',$detailParams) }}" title="Lihat transaksi arus kas">{{ $fmt($row['total']) }}</a>@else{{ $fmt($row['total']) }}@endif</td></tr>@endforeach
                <tr class="total-row"><td>Jumlah Arus Kas Masuk</td>@foreach($periods as $period)<td class="amount">{{ $fmt($result['incomingTotals'][$period->format('Y-m')] ?? 0) }}</td>@endforeach<td class="amount">{{ $fmt($result['totalIncoming']) }}</td></tr>
                <tr class="section-row"><td colspan="{{ $periods->count()+2 }}">ARUS KAS KELUAR</td></tr>
                @foreach($result['outgoingRows'] as $row)<tr class="cash-account-row" data-search="{{ strtolower($row['kode'].' '.$row['nama']) }}"><td><strong>{{ $row['nama'] }}</strong><small class="d-block text-muted">{{ $row['kode'] }}</small></td>@foreach($periods as $period)@php $amount=$row['values'][$period->format('Y-m')] ?? 0; $detailParams=['akun_kas'=>$selectedAccount->id_akun_perkiraan,'akun_lawan'=>$row['id'],'kategori'=>$row['kategori_utang'] ?? '','nilai'=>$amount,'tanggal_awal'=>$period->copy()->startOfMonth()->toDateString(),'tanggal_akhir'=>$period->copy()->endOfMonth()->toDateString()]; @endphp<td class="amount">@if($row['id'])<a href="{{ route('jurnal-perkiraan.arus-kas-detail',$detailParams) }}" title="Lihat transaksi arus kas">{{ $fmt($amount) }}</a>@else{{ $fmt($amount) }}@endif</td>@endforeach@php $detailParams=['akun_kas'=>$selectedAccount->id_akun_perkiraan,'akun_lawan'=>$row['id'],'kategori'=>$row['kategori_utang'] ?? '','nilai'=>$row['total'],'tanggal_awal'=>$start->toDateString(),'tanggal_akhir'=>$end->toDateString()]; @endphp<td class="amount fw-bold">@if($row['id'])<a href="{{ route('jurnal-perkiraan.arus-kas-detail',$detailParams) }}" title="Lihat transaksi arus kas">{{ $fmt($row['total']) }}</a>@else{{ $fmt($row['total']) }}@endif</td></tr>@endforeach
                <tr class="total-row"><td>Jumlah Arus Kas Keluar</td>@foreach($periods as $period)<td class="amount">{{ $fmt($result['outgoingTotals'][$period->format('Y-m')] ?? 0) }}</td>@endforeach<td class="amount">{{ $fmt($result['totalOutgoing']) }}</td></tr>
                <tr class="section-row"><td colspan="{{ $periods->count()+2 }}">RINGKASAN</td></tr><tr class="total-row"><td>Arus Kas Bersih</td>@foreach($periods as $period)<td class="amount">{{ $fmt($result['netTotals'][$period->format('Y-m')] ?? 0) }}</td>@endforeach<td class="amount">{{ $fmt($result['totalIncoming']-$result['totalOutgoing']) }}</td></tr>
            </tbody></table></div>
            <p class="text-muted small mt-2 mb-0">Akun lawan dihitung dari jurnal perkiraan aktif pada transaksi yang memengaruhi akun kas/bank yang dipilih.</p>
        @else
            <div class="text-center text-muted py-5"><i class="fas fa-university fa-3x mb-3"></i><p>Belum ada akun kas atau bank yang memiliki jurnal.</p></div>
        @endif
        <script>document.addEventListener('DOMContentLoaded',function(){const input=document.getElementById('cariArusKas');if(input){const rows=[...document.querySelectorAll('.cash-account-row')];input.addEventListener('input',function(){const q=this.value.toLowerCase().trim();let n=0;rows.forEach(r=>{const ok=!q||r.dataset.search.includes(q);r.classList.toggle('d-none',!ok);if(ok)n++});document.getElementById('hasilArusKas').textContent=q?n+' akun ditemukan':''})}const cashIds=@json($akunKasDetail);if(cashIds.length>1){document.querySelectorAll('.cash-table .amount a').forEach(a=>{const u=new URL(a.href,window.location.origin);u.searchParams.delete('akun_kas');cashIds.forEach(id=>u.searchParams.append('akun_kas[]',id));a.href=u.toString()})}});</script>
    </x-slot>
</x-theme.app>
