<x-theme.app title="Tambah Uang Muka Pullet" table="Y" sizeCard="8">
    <x-slot name="cardHeader">
        <div class="d-flex justify-content-between align-items-center">
            <div><h5 class="mb-1">Tambah Uang Muka Pullet</h5><small class="text-muted">{{ $p->nomor }} — {{ $p->nama_pullet }}</small></div>
            <a href="{{ route('pembelian-pullet.index') }}" class="btn btn-outline-primary btn-sm"><i class="fas fa-arrow-left me-1"></i>Kembali</a>
        </div>
    </x-slot>
    <x-slot name="cardBody">
        @php($sisa = max((float)$p->total_nilai - (float)($p->total_dibayar ?? 0), 0))
        <style>.debt-info{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px}.debt-item{padding:14px;border:1px solid #dce3f2;border-radius:10px;background:#f5f7fc}.debt-item small{display:block;color:#718096}.debt-item strong{color:#29468f;font-size:18px}.pay-box{padding:18px;border:1px solid #dce3f2;border-radius:12px}.pay-box .form-label{font-size:12px;font-weight:700;color:#536078}.select2-container{width:100%!important}@media(max-width:600px){.debt-info{grid-template-columns:1fr}}</style>
        <div class="debt-info"><div class="debt-item"><small>Total pembelian</small><strong>Rp {{ number_format($p->total_nilai,0,',','.') }}</strong></div><div class="debt-item"><small>Uang muka terkumpul</small><strong>Rp {{ number_format($p->total_dibayar ?? 0,0,',','.') }}</strong></div><div class="debt-item"><small>Sisa pembayaran</small><strong>Rp {{ number_format($sisa,0,',','.') }}</strong></div></div>
        <form method="POST" action="{{ route('pembelian-pullet.store-cicilan',$p->id) }}" class="pay-box">@csrf
            <div class="row g-3"><div class="col-md-4"><label class="form-label">Tanggal pembayaran</label><input type="date" name="tanggal" class="form-control" value="{{ old('tanggal',now()->toDateString()) }}" required></div><div class="col-md-4"><label class="form-label">Nilai uang muka lanjutan</label><input type="number" name="nominal" class="form-control" min="1" max="{{ $sisa }}" value="{{ old('nominal') }}" required></div><div class="col-md-4"><label class="form-label">Dibayar dari</label><select name="id_akun_pembayaran" class="form-select select-search" required><option value="">Pilih kas/bank</option>@foreach($accounts as $a)<option value="{{ $a->id_akun_perkiraan }}">{{ $a->kode_perkiraan }} - {{ $a->nama }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Keterangan / catatan cicilan</label><textarea name="keterangan" class="form-control" rows="3" maxlength="1000" placeholder="Contoh: Pembayaran tahap kedua">{{ old('keterangan') }}</textarea></div></div>
            <div class="alert alert-light border mt-3 mb-0"><b>Jurnal:</b> Debit Uang Muka Pembelian IDR, Kredit akun kas/bank yang dipilih.</div>
            <div class="text-end mt-3"><button class="btn btn-primary"><i class="fas fa-save me-1"></i>Simpan Pembayaran</button></div>
        </form>
        <div class="mt-4"><div class="d-flex justify-content-between align-items-center mb-2"><div><h6 class="mb-1">Riwayat Pembayaran</h6><small class="text-muted">Pembayaran pertama dan pembayaran lanjutan dapat diedit selama belum masuk kandang.</small></div></div><div class="table-responsive border rounded"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>No</th><th>Tanggal</th><th>Nomor</th><th>Akun Pembayaran</th><th>Keterangan</th><th class="text-end">Nominal</th><th>Aksi</th></tr></thead><tbody>@forelse($pembayaran as $i=>$bayar)<tr><td>{{ $i+1 }}</td><td>{{ tanggal($bayar->tanggal) }}</td><td>{{ $bayar->nomor_transaksi }}</td><td>{{ $bayar->kode_perkiraan }} - {{ $bayar->nama_akun }}</td><td>{{ $bayar->keterangan ?: '-' }}</td><td class="text-end">Rp {{ number_format($bayar->nominal,0,',','.') }}</td><td><a href="{{ route('pembelian-pullet.edit-pembayaran',[$p->id,$bayar->id]) }}" class="btn btn-outline-warning btn-sm"><i class="fas fa-edit me-1"></i>Edit</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada riwayat pembayaran.</td></tr>@endforelse</tbody></table></div></div>
        <script>$(function(){if($.fn.select2)$('.select-search').select2({width:'100%'});});</script>
    </x-slot>
</x-theme.app>
