<x-theme.app title="Pullet Masuk Kandang" table="Y" sizeCard="8">
    <x-slot name="cardHeader"><div class="d-flex justify-content-between align-items-center"><div><h5 class="mb-1">Pullet Masuk Kandang</h5><small class="text-muted">Pembalikan uang muka menjadi Persediaan Ayam</small></div><a href="{{ route('pembelian-pullet.index') }}" class="btn btn-outline-primary btn-sm">Kembali</a></div></x-slot>
    <x-slot name="cardBody">
        @php($sisaHutang = max((float)$p->total_nilai - (float)($p->total_dibayar ?? 0),0))
        @if(isset($errors) && $errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="row g-2 mb-3"><div class="col-md-4"><div class="p-3 border rounded bg-light"><small>Total pembelian</small><strong class="d-block text-primary">Rp {{ number_format($p->total_nilai,0,',','.') }}</strong></div></div><div class="col-md-4"><div class="p-3 border rounded bg-light"><small>Uang muka terkumpul</small><strong class="d-block text-primary">Rp {{ number_format($p->total_dibayar ?? 0,0,',','.') }}</strong></div></div><div class="col-md-4"><div class="p-3 border rounded bg-light"><small>Sisa pembayaran</small><strong class="d-block {{ $sisaHutang>0?'text-danger':'text-success' }}">Rp {{ number_format($sisaHutang,0,',','.') }}</strong></div></div></div>
        @if($sisaHutang > 0)<div class="alert alert-warning">Lunasi uang muka pullet terlebih dahulu sebelum dipindahkan ke kandang. <a href="{{ route('pembelian-pullet.cicilan',$p->id) }}" class="alert-link">Bayar sekarang</a>.</div>@endif
        <form method="POST" action="{{ route('pembelian-pullet.store-finalize',$p->id) }}" class="p-3 border rounded">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label">Nama kandang</label><input class="form-control bg-light" value="{{ $p->nama_pullet }}" readonly><small class="text-muted">Otomatis diambil dari nama/kelompok pullet.</small></div><div class="col-md-6"><label class="form-label">Strain ayam</label><select name="id_strain" class="form-select select-search" required><option value="">-- Cari dan pilih strain --</option>@foreach($strains as $strain)<option value="{{ $strain->id_strain }}" @selected(old('id_strain')==$strain->id_strain)>{{ $strain->nm_strain }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Tanggal masuk kandang</label><input type="date" name="tanggal" class="form-control" value="{{ old('tanggal',now()->toDateString()) }}" required></div><div class="col-md-6"><label class="form-label">Jumlah ayam (ekor)</label><input type="number" name="qty" class="form-control" min="1" step="1" value="{{ old('qty') }}" required></div></div><div class="alert alert-light border mt-3"><b>Jurnal pembalikan:</b> Debit Persediaan Ayam, Kredit Uang Muka Pembelian IDR.</div><div class="text-end"><button class="btn btn-success" @disabled($sisaHutang > 0)><i class="fas fa-exchange-alt me-1"></i>Masukkan ke Kandang</button></div></form>
    </x-slot>
    @section('scripts')<script>if(window.jQuery&&jQuery.fn.select2)jQuery('.select-search').select2({width:'100%',placeholder:'Cari dan pilih strain',allowClear:true});</script>@endsection
</x-theme.app>
